apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.10.1
    chart: prometheus
    helm:
      values: |
        server:
          persistentVolume:
            storageClass: "local-storage"
          service:
            type: NodePort
            nodePort: 30090
        alertmanager:
          persistentVolume:
            storageClass: "local-storage"
        pushgateway:
          persistentVolume:
            storageClass: "local-storage"
        nodeExporter:
          hostRootfs: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
