apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charttest1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/soundn/Task-repo.git
    targetRevision: main
    path: HelmCharts/ChartTest1
    helm:
      valueFiles:
      - values_dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
